# ci/tasks/package.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
- name: source-code

run:
  path: /bin/sh
  args: ["source-code/ci/tasks/package.sh"]
