# ci/resources.yml

resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/AureaMohammadAlavi/spring-boot-demo
    branch: master
- name: myapp-image
  type: docker-image
  source:
    username: smash1986
    password: 123!@#abc8
    repository: smash1986/fuckyou


jobs:
  - name: package
    plan:
      - get: source-code
        trigger: true
      - task: package
        privileged: true
        file: source-code/ci/tasks/package.yml
      - put: myapp-image
        params:
          build: source-code
          build_args:
            JAR_FILE: source-code/target/spring-demo-1.0-SNAPSHOT.jar